version: '3.8'

services:
  springboot-1:
    image: gitlab.fiipractic.lan:5050/root/springboot:latest
    container_name: springboot-1
    restart: always
    ports:
      - "8081:8080"
    environment:
      - SERVER_PORT=8080

  springboot-2:
    image: gitlab.fiipractic.lan:5050/root/springboot:latest
    container_name: springboot-2
    restart: always
    ports:
      - "8082:8080"
    environment:
      - SERVER_PORT=8080

  nginx:
    image: nginx:alpine
    container_name: nginx-lb
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx-lesson4.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - springboot-1
      - springboot-2
